name: Sync LeetCode Solutions

on:
  schedule:
    - cron: "0 0 * * *" # Run daily at midnight UTC
  workflow_dispatch: # Allows manual triggering from the GitHub Actions tab

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install leetcode-cli
        run: npm install -g leetcode-cli

      - name: Log in to LeetCode
        env:
          LEETCODE_USERNAME: ${{ secrets.LEETCODE_USERNAME }}
          LEETCODE_PASSWORD: ${{ secrets.LEETCODE_PASSWORD }}
        run: |
          leetcode user -l --username "$LEETCODE_USERNAME" --password "$LEETCODE_PASSWORD"

      - name: Fetch and filter solutions
        run: |
          mkdir -p filtered_solutions
          leetcode submissions -x
          for file in .leetcode/*.json; do
            # Check for all tests passing in the submission JSON
            if jq -e '.status == "Accepted"' "$file" > /dev/null; then
              cp "$file" filtered_solutions/
            fi
          done

      - name: Commit and push passing solutions
        if: success() && steps.fetch_outputs.outputs.filtered_solutions != ''
        run: |
          git config user.name "leetcode-bot"
          git config user.email "bot@example.com"
          git add filtered_solutions/*
          git commit -m "Automated update of passing LeetCode solutions"
          git push
